import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>
          Go to <pre>[...slug].tsx</pre> so everything is ran within a global route.<br/>
        </p>
        <p>
          Going to <pre>/fill</pre> it will instanciate the routes. <a href="/fill">Here</a><br/>
          Going to <pre>/show</pre> it will just read the routes available without. <a href="/show">Here</a><br/>
          Going to <pre>/api/hello</pre> it will show the result in the API route. <a href="/api/hello">Here</a><br/>
          Going to <pre>/show</pre> it will just reset factory. <a href="/reset">Here</a><br/>
        </p>
      </main>
    </>
  )
}